### PR TITLE
removing space from rustc version command

### PR DESCRIPTION
**Pull request by pandapaul**
I know absolutely nothing about rust (yet!) but it seems like `rustc --version` works while `rustc -- version` (with -- and version separated by a space) doesn't.

### CODE REVIEW

**Comment by pandapaul** [comment]
Actually seems like this was already addressed in https://github.com/ashleygwilliams/a-very-brief-intro-to-rust/pull/8

**Comment by ashleygwilliams** [comment]
👍 thanks anyways!

**Comment by ashleygwilliams** [comment]
actually! this changes it in the slides and is still needed! thank you!

**Comment by pandapaul** [comment]
Oh good deal.  Thanks!

**Pull request merged**
